### ISSUE TITLE
Loot table not loading properly

### ISSUE THREAD

**Issue by edgaradr223** [Spectre0987/PirateMod#11]
[2019-05-13-3.log](https://github.com/Spectre0987/PirateMod/files/3174878/2019-05-13-3.log)

Hello Bro, this is the log, as i explained before there is a problem loading the loot table, (I use the last version of Forge and over 150 mods) thank you for your help :)

**Comment by Spectre0987** [comment]
Yes! I've had people complain about this before, but I wasn't having this issue and they wouldn't provide a log. This, however, contains exactly what I need! Thanks!

**Comment by Spectre0987** [comment]
Nevermind, you were using an old version. This is fixed in 0.0.5
