### ISSUE TITLE
New cannon system doesn't function at all

### ISSUE THREAD

**Issue by DWX12** [Spectre0987/PirateMod#7]
Tried using the new cannon system and no matter what order I used the items, nothing seems to work nor can I seem to add any items into the cannon.

Might just be that it's still a work in progress and not functioning just yet or I'm doing something incorrectly.

**Comment by Spectre0987** [comment]
It does. You put in gunpowder, use the ramrod, add a cannon ball, then light it with a flint and steel

**Comment by DWX12** [comment]
Will try it again with the new version to see if I can get it to work when I take the opportunity to.

**Comment by DWX12** [comment]
You were correct, for whatever reason I was trying to use the powder flask instead of actual gun powder. Seems that any more than three gun powder put in will make the cannon explode when used, which I assume is intentional.

Maybe a similar mechanic could be applied to the flint lock pistol.
