### ISSUE TITLE
[Bug] Telescope does not zoom in nor does upgrading it do anything

### ISSUE THREAD

**Issue by DWX12** [Spectre0987/PirateMod#9]
Currently the telescope only causes the edges of the screen to go black when interacted with/right click is held down (working as intended); however, there is no zoom to it no matter how many glass panes are crafted with it.

There is also no JEI recipe for extending the zoom with glass panes. Glass panes can also be forever added to the telescope, which only increase its zoom number and nothing more.

**Comment by Spectre0987** [comment]
What other mods do you have?

**Comment by Spectre0987** [comment]
As it works for everyone else, and you've provided no extra info, I'll have to just close this
